# -*- coding: utf-8 -*-
"""iris classifier model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7WRDNXUi6hUS3klu7lPVbzGmTPpk5EE
"""

# Project 2: Data Classification Using AI
## Iris Flower Classification

### Objective
#Build a basic classification model using the Iris dataset.

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import os

print(os.listdir('/content/drive/MyDrive'))

print(os.listdir('/content/drive/MyDrive/iris'))

# Load Iris dataset
file_path = '/content/drive/MyDrive/iris/iris.data'

columns = [
    'sepal_length',
    'sepal_width',
    'petal_length',
    'petal_width',
    'species'
]

df = pd.read_csv(file_path, header=None, names=columns)

df.head()

# Dataset ki basic information
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nSpecies:")
print(df["species"].value_counts())

print("\nMissing values:")
print(df.isnull().sum())

# Features (X)
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

# Target / Label (y)
y = df['species']

# Train-Test Split: 70% training, 30% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create SVM model
svm_model = SVC(
    kernel='rbf',
    C=1,
    gamma='scale'
)

# Train the model
svm_model.fit(X_train_scaled, y_train)

# Make predictions on test data
y_pred = svm_model.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)
print("Test Accuracy (%):", accuracy * 100)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))